COL_NAME_REPLACEMENTS = {
    "+/-": "PLUS_MINUS"
}
INDEPENDENT_BOX_COLS = [
    'PTS', 'FGA', 'FG_P', '3PA', '3P_P', 'FTA', 'FT_P', 'OREB', 'DREB',
    'REB', 'AST', 'TOV', 'STL', 'BLK', 'PF'
]
DEPENDENT_BOX_COL = 'PLUS_MINUS'